### ISSUE TITLE
Auto-display the 'subject' (directory) when rendering a note

### ISSUE THREAD

**Issue by glenshelly** [nathanshelly/totes#33]
Showing the subject (e.g., "vim") somehow in the display will enable a couple things: 

1. Give the user a quick, consistent context for what they're about to read, and relieve the actual note from needing to do that

2. Announce/re-inforce the particular subject naming in case the user wants to type it in explicitly later as a parameter to totes

**Comment by glenshelly** [comment]
@nathanshelly What do you think about this issue?

**Comment by glenshelly** [comment]
Hmm, I'm not seeing a good way to do with, when the screen could be filled up - I'm thinking this might not be worth doing

**Comment by nathanshelly** [comment]
makes sense to me, maybe best thing we can do is solidify the first line convention (could be part of the style guide) that's so far been followed?

```markdown
# SUBJECT - Note Title
```

**Comment by glenshelly** [comment]
I'm going to close this for now, based on the discussion above.
